data_config: &data_config
  type: "reddit_bias_data"
  debug: false
  subset_size: 10
  category: ["gender", "race", "religion_jc", "religion_mc"] # ["gender", "race", "religion_jc", "religion_mc", "orientation"]

config:
  run_id: 1
  seed: 36
  benchmark_configs:
    - name: "reddit_bias"
      type: "reddit_bias"
      provider: "local"
      data_config: *data_config
      num_workers: 1
      postprocessor: 
        type: "reformat_counterfactual_sentences"

info:
  license: "MIT License"
  source: "https://github.com/SoumyaBarikeri/RedditBias"