data_config: &data_config
  type: "stereo_set_data"
  debug: false
  subset_size: 10
  category: ["gender", "race", "religion"] # ["gender", "race", "religion", "profession"]

config:
  run_id: 1
  seed: 36
  benchmark_configs:
    - name: "stereo_set"
      type: "stereo_set"
      provider: "local"
      data_config: *data_config
      num_workers: 1
      postprocessor: 
        type: "reformat_counterfactual_sentences"

info:
  license: "MIT License"
  source: "https://github.com/moinnadeem/StereoSet/"