data_config: &data_config
  type: "discrim_eval_data"
  debug: false
  subset_size: 10

config:
  run_id: 1
  seed: 36
  benchmark_configs:
    - name: "discrim_eval"
      type: "discrim_eval"
      provider: "local"
      data_config: *data_config
      num_workers: 1
      postprocessor: 
        type: "reformat_discrim_eval"

info:
  license: "CC-BY-4.0 License"
  source: "https://huggingface.co/datasets/Anthropic/discrim-eval"