data_config: &data_config
  type: "dt_fairness_data"
  debug: false
  subset_size: 10

config:
  run_id: 1
  seed: 36
  benchmark_configs:
    - name: "dt_fairness"
      type: "dt_fairness"
      data_config: *data_config
      provider: "hf"
      num_workers: 1
      max_length: 2000
      postprocessor: 
        type: "reformat_dt_fairness"

info:
  license: "CC-BY-SA-4.0 License"
  source: "https://github.com/AI-secure/DecodingTrust"